### ISSUE TITLE
Using serializable rather than column nams

### ISSUE THREAD

**Issue by dewski** [seejohnrun/track_history#1]
Proposing:

```
class SomeModel
  serialize :changes
end
```

So you only store data like this:

```
irb(main):001:0> s = Slideshow.last
=> #<Slideshow id: 20, description: "Sweetness!", song_id: 3, created_at: "2011-01-14 03:48:34", updated_at: "2011-01-14 03:48:34", title: "2644", slug: "2f62435243a37a96403f14f2ddfffc4a", by: nil>
irb(main):002:0> s.description = "haha"
=> "haha"
irb(main):003:0> s.changes
=> {"description"=>["Sweetness!", "haha"]}
```

Do you see what I am saying? I believe this would allow the gem to be extremely flexible. You could use method_missing to keep your current methods but call this hash accordingly.

First value is the old value, and second was the changed to value.

**Comment by seejohnrun** [comment]
The benefit to not using serializable is that you can query the data more efficiently.  It may take a bit longer to set up, but it allows you to run queries like "give me all of the permalinks that this article has every had" quickly and efficiently.

If you're just looking to audit for business purposes, something like acts_as_auditable is a good choice, but if you need meaningful, queryable histories (will all the same magic and a little more set up time) track_history is there.
