### ISSUE TITLE
uninitialized constant TrackHistory::ActsAsMethods::HistoryMethods

### ISSUE THREAD

**Issue by yangjiandong** [seejohnrun/track_history#2]
in jruby1.6rc1,rails3.0.1,sqlite3, gem 'track_history', '0.0.10'
model:
class Post < ActiveRecord::Base
  track_history
end
migration:
    create_table 'post_histories' do |t|
      t.column :post_id, :integer
      t.column :title_before,  :string, :limit => 255
      t.column :title_after, :string, :limit => 255
      t.column :created_at, :datetime
    end

in controller,use @post = Post.new,it will show error:
uninitialized constant TrackHistory::ActsAsMethods::HistoryMethods

**Comment by seejohnrun** [comment]
This should be fixed now (v0.0.11 pushed momentarily) - looked like an auto-loading issue - thanks for the details on your environment, that helped a lot.

Let me know if you still experience issues

**Comment by yangjiandong** [comment]
update to 0.0.11,it's ok.
thank you,it's cool!
another question,how to write migration for track history,now i use :
create_table 'post_histories' do |t|
      t.column :post_id, :integer
      t.column :title_before,  :string, :limit => 255
      t.column :title_after, :string, :limit => 255
      t.column :created_at, :datetime
how to auto create mode migration?

**Comment by seejohnrun** [comment]
Glad that worked for you -- 
Yep, by hand for now, a generator will be coming soon
