### ISSUE TITLE
no issue, just a thanks, and a monkey-patch

### ISSUE THREAD

**Issue by 4fthawaiian** [seejohnrun/track_history#4]
Howdy,

Just wanted to tell you how much I dig this gem, and how crucial it's been to the project I'm working on (an asset management frontend and api for my work). I wrote a quick patch to AR to automagically create the history tables, and thought it might interest you:

class ActiveRecord::Schema
  def create_history(table_name)
    table = table_name.to_s
    model = eval table.classify
    single_table_name = table.gsub /s$/, ''
    history_table = single_table_name+"_histories"
    create_table history_table, :force => true do |d|
      d.column single_table_name+"_id", :integer
      model.columns.each do |model_column|
        next if model_column.name == "id"
        ["before", "after"].each do |bae|
          d.column model_column.name+"_#{bae}", model_column.type, :limit => model_column.limit
        end
      end
    end
  end
end

I'm fairly new to ruby, so I'm sure it could be much better, but I thought you'd like to see how I've worked this into my code. 

Thanks again for a great gem!

Cheers,
Bradley

**Comment by seejohnrun** [comment]
Thanks for the kind words! Would be cool if this was a generator in rails.
Great idea

Sent from my iPhone

On Jan 3, 2013, at 10:20 AM, Bradley McCrorey notifications@github.com
wrote:

Howdy,

Just wanted to tell you how much I dig this gem, and how crucial it's been
to the project I'm working on (an asset management frontend and api for my
work). I wrote a quick patch to AR to automagically create the history
tables, and thought it might interest you:

class ActiveRecord::Schema
def create_history(table_name)
table = table_name.to_s
model = eval table.classify
single_table_name = table.gsub /s$/, ''
history_table = single_table_name+"_histories"
create_table history_table, :force => true do |d|
d.column single_table_name+"_id", :integer
model.columns.each do |model_column|
next if model_column.name == "id"
["before", "after"].each do |bae|
d.column model_column.name+"_#{bae}", model_column.type, :limit =>
model_column.limit
end
end
end
end
end

I'm fairly new to ruby, so I'm sure it could be much better, but I thought
you'd like to see how I've worked this into my code.

Thanks again for a great gem!

Cheers,
Bradley

—
Reply to this email directly or view it on
GitHubhttps://github.com/seejohnrun/track_history/issues/4.

**Comment by seejohnrun** [comment]
Closing this down - thank you again for the code - if someone wants to convert this to a Rails generator some day, PR welcome!  Thanks!
